// Auto generated constants from LuxandFaceSDK.h

// enum FSDK_VIDEOCOMPRESSIONTYPE
pub const FSDK_MJPEG: i32 = 0;

// enum FSDK_IMAGEMODE
pub const FSDK_IMAGE_GRAYSCALE_8BIT: i32 = 0;
pub const FSDK_IMAGE_COLOR_24BIT: i32 = 1;
pub const FSDK_IMAGE_COLOR_32BIT: i32 = 2;

// Error codes
pub const FSDKE_OK: i32 = 0;
pub const FSDKE_FAILED: i32 = -1;
pub const FSDKE_NOT_ACTIVATED: i32 = -2;
pub const FSDKE_OUT_OF_MEMORY: i32 = -3;
pub const FSDKE_INVALID_ARGUMENT: i32 = -4;
pub const FSDKE_IO_ERROR: i32 = -5;
pub const FSDKE_IMAGE_TOO_SMALL: i32 = -6;
pub const FSDKE_FACE_NOT_FOUND: i32 = -7;
pub const FSDKE_INSUFFICIENT_BUFFER_SIZE: i32 = -8;
pub const FSDKE_UNSUPPORTED_IMAGE_EXTENSION: i32 = -9;
pub const FSDKE_CANNOT_OPEN_FILE: i32 = -10;
pub const FSDKE_CANNOT_CREATE_FILE: i32 = -11;
pub const FSDKE_BAD_FILE_FORMAT: i32 = -12;
pub const FSDKE_FILE_NOT_FOUND: i32 = -13;
pub const FSDKE_CONNECTION_CLOSED: i32 = -14;
pub const FSDKE_CONNECTION_FAILED: i32 = -15;
pub const FSDKE_IP_INIT_FAILED: i32 = -16;
pub const FSDKE_NEED_SERVER_ACTIVATION: i32 = -17;
pub const FSDKE_ID_NOT_FOUND: i32 = -18;
pub const FSDKE_ATTRIBUTE_NOT_DETECTED: i32 = -19;
pub const FSDKE_INSUFFICIENT_TRACKER_MEMORY_LIMIT: i32 = -20;
pub const FSDKE_UNKNOWN_ATTRIBUTE: i32 = -21;
pub const FSDKE_UNSUPPORTED_FILE_VERSION: i32 = -22;
pub const FSDKE_SYNTAX_ERROR: i32 = -23;
pub const FSDKE_PARAMETER_NOT_FOUND: i32 = -24;
pub const FSDKE_INVALID_TEMPLATE: i32 = -25;
pub const FSDKE_UNSUPPORTED_TEMPLATE_VERSION: i32 = -26;
pub const FSDKE_CAMERA_INDEX_DOES_NOT_EXIST: i32 = -27;
pub const FSDKE_PLATFORM_NOT_LICENSED: i32 = -28;
pub const FSDKE_TENSORFLOW_NOT_INITIALIZED: i32 = -29;
pub const FSDKE_PLUGIN_NOT_LOADED: i32 = -30;
pub const FSDKE_PLUGIN_NO_PERMISSION: i32 = -31;
pub const FSDKE_FACEID_NOT_FOUND: i32 = -32;
pub const FSDKE_FACEIMAGE_NOT_FOUND: i32 = -33;
pub const FSDKE_IBETA_INITIALIZATION_ERROR: i32 = -200;

// Facial feature count
pub const FSDK_FACIAL_FEATURE_COUNT: usize = 70;

// Facial features
pub const FSDKP_LEFT_EYE: usize = 0;
pub const FSDKP_RIGHT_EYE: usize = 1;
pub const FSDKP_LEFT_EYE_INNER_CORNER: usize = 24;
pub const FSDKP_LEFT_EYE_OUTER_CORNER: usize = 23;
pub const FSDKP_LEFT_EYE_LOWER_LINE1: usize = 38;
pub const FSDKP_LEFT_EYE_LOWER_LINE2: usize = 27;
pub const FSDKP_LEFT_EYE_LOWER_LINE3: usize = 37;
pub const FSDKP_LEFT_EYE_UPPER_LINE1: usize = 35;
pub const FSDKP_LEFT_EYE_UPPER_LINE2: usize = 28;
pub const FSDKP_LEFT_EYE_UPPER_LINE3: usize = 36;
pub const FSDKP_LEFT_EYE_LEFT_IRIS_CORNER: usize = 29;
pub const FSDKP_LEFT_EYE_RIGHT_IRIS_CORNER: usize = 30;
pub const FSDKP_RIGHT_EYE_INNER_CORNER: usize = 25;
pub const FSDKP_RIGHT_EYE_OUTER_CORNER: usize = 26;
pub const FSDKP_RIGHT_EYE_LOWER_LINE1: usize = 41;
pub const FSDKP_RIGHT_EYE_LOWER_LINE2: usize = 31;
pub const FSDKP_RIGHT_EYE_LOWER_LINE3: usize = 42;
pub const FSDKP_RIGHT_EYE_UPPER_LINE1: usize = 40;
pub const FSDKP_RIGHT_EYE_UPPER_LINE2: usize = 32;
pub const FSDKP_RIGHT_EYE_UPPER_LINE3: usize = 39;
pub const FSDKP_RIGHT_EYE_LEFT_IRIS_CORNER: usize = 33;
pub const FSDKP_RIGHT_EYE_RIGHT_IRIS_CORNER: usize = 34;
pub const FSDKP_LEFT_EYEBROW_INNER_CORNER: usize = 13;
pub const FSDKP_LEFT_EYEBROW_MIDDLE: usize = 16;
pub const FSDKP_LEFT_EYEBROW_MIDDLE_LEFT: usize = 18;
pub const FSDKP_LEFT_EYEBROW_MIDDLE_RIGHT: usize = 19;
pub const FSDKP_LEFT_EYEBROW_OUTER_CORNER: usize = 12;
pub const FSDKP_RIGHT_EYEBROW_INNER_CORNER: usize = 14;
pub const FSDKP_RIGHT_EYEBROW_MIDDLE: usize = 17;
pub const FSDKP_RIGHT_EYEBROW_MIDDLE_LEFT: usize = 20;
pub const FSDKP_RIGHT_EYEBROW_MIDDLE_RIGHT: usize = 21;
pub const FSDKP_RIGHT_EYEBROW_OUTER_CORNER: usize = 15;
pub const FSDKP_NOSE_TIP: usize = 2;
pub const FSDKP_NOSE_BOTTOM: usize = 49;
pub const FSDKP_NOSE_BRIDGE: usize = 22;
pub const FSDKP_NOSE_LEFT_WING: usize = 43;
pub const FSDKP_NOSE_LEFT_WING_OUTER: usize = 45;
pub const FSDKP_NOSE_LEFT_WING_LOWER: usize = 47;
pub const FSDKP_NOSE_RIGHT_WING: usize = 44;
pub const FSDKP_NOSE_RIGHT_WING_OUTER: usize = 46;
pub const FSDKP_NOSE_RIGHT_WING_LOWER: usize = 48;
pub const FSDKP_MOUTH_RIGHT_CORNER: usize = 3;
pub const FSDKP_MOUTH_LEFT_CORNER: usize = 4;
pub const FSDKP_MOUTH_TOP: usize = 54;
pub const FSDKP_MOUTH_TOP_INNER: usize = 61;
pub const FSDKP_MOUTH_BOTTOM: usize = 55;
pub const FSDKP_MOUTH_BOTTOM_INNER: usize = 64;
pub const FSDKP_MOUTH_LEFT_TOP: usize = 56;
pub const FSDKP_MOUTH_LEFT_TOP_INNER: usize = 60;
pub const FSDKP_MOUTH_RIGHT_TOP: usize = 57;
pub const FSDKP_MOUTH_RIGHT_TOP_INNER: usize = 62;
pub const FSDKP_MOUTH_LEFT_BOTTOM: usize = 58;
pub const FSDKP_MOUTH_LEFT_BOTTOM_INNER: usize = 63;
pub const FSDKP_MOUTH_RIGHT_BOTTOM: usize = 59;
pub const FSDKP_MOUTH_RIGHT_BOTTOM_INNER: usize = 65;
pub const FSDKP_NASOLABIAL_FOLD_LEFT_UPPER: usize = 50;
pub const FSDKP_NASOLABIAL_FOLD_LEFT_LOWER: usize = 52;
pub const FSDKP_NASOLABIAL_FOLD_RIGHT_UPPER: usize = 51;
pub const FSDKP_NASOLABIAL_FOLD_RIGHT_LOWER: usize = 53;
pub const FSDKP_CHIN_BOTTOM: usize = 11;
pub const FSDKP_CHIN_LEFT: usize = 9;
pub const FSDKP_CHIN_RIGHT: usize = 10;
pub const FSDKP_FACE_CONTOUR1: usize = 7;
pub const FSDKP_FACE_CONTOUR2: usize = 5;
pub const FSDKP_FACE_CONTOUR12: usize = 6;
pub const FSDKP_FACE_CONTOUR13: usize = 8;
pub const FSDKP_FACE_CONTOUR14: usize = 66;
pub const FSDKP_FACE_CONTOUR15: usize = 67;
pub const FSDKP_FACE_CONTOUR16: usize = 68;
pub const FSDKP_FACE_CONTOUR17: usize = 69;

// FSDK_FaceTemplate size
pub const FSDK_FACE_TEMPLATE_SIZE: usize = 2068;

pub fn error_name(code: i32) -> &'static str {
    match code {
        FSDKE_OK => "FSDKE_OK",
        FSDKE_FAILED => "FSDKE_FAILED",
        FSDKE_NOT_ACTIVATED => "FSDKE_NOT_ACTIVATED",
        FSDKE_OUT_OF_MEMORY => "FSDKE_OUT_OF_MEMORY",
        FSDKE_INVALID_ARGUMENT => "FSDKE_INVALID_ARGUMENT",
        FSDKE_IO_ERROR => "FSDKE_IO_ERROR",
        FSDKE_IMAGE_TOO_SMALL => "FSDKE_IMAGE_TOO_SMALL",
        FSDKE_FACE_NOT_FOUND => "FSDKE_FACE_NOT_FOUND",
        FSDKE_INSUFFICIENT_BUFFER_SIZE => "FSDKE_INSUFFICIENT_BUFFER_SIZE",
        FSDKE_UNSUPPORTED_IMAGE_EXTENSION => "FSDKE_UNSUPPORTED_IMAGE_EXTENSION",
        FSDKE_CANNOT_OPEN_FILE => "FSDKE_CANNOT_OPEN_FILE",
        FSDKE_CANNOT_CREATE_FILE => "FSDKE_CANNOT_CREATE_FILE",
        FSDKE_BAD_FILE_FORMAT => "FSDKE_BAD_FILE_FORMAT",
        FSDKE_FILE_NOT_FOUND => "FSDKE_FILE_NOT_FOUND",
        FSDKE_CONNECTION_CLOSED => "FSDKE_CONNECTION_CLOSED",
        FSDKE_CONNECTION_FAILED => "FSDKE_CONNECTION_FAILED",
        FSDKE_IP_INIT_FAILED => "FSDKE_IP_INIT_FAILED",
        FSDKE_NEED_SERVER_ACTIVATION => "FSDKE_NEED_SERVER_ACTIVATION",
        FSDKE_ID_NOT_FOUND => "FSDKE_ID_NOT_FOUND",
        FSDKE_ATTRIBUTE_NOT_DETECTED => "FSDKE_ATTRIBUTE_NOT_DETECTED",
        FSDKE_INSUFFICIENT_TRACKER_MEMORY_LIMIT => "FSDKE_INSUFFICIENT_TRACKER_MEMORY_LIMIT",
        FSDKE_UNKNOWN_ATTRIBUTE => "FSDKE_UNKNOWN_ATTRIBUTE",
        FSDKE_UNSUPPORTED_FILE_VERSION => "FSDKE_UNSUPPORTED_FILE_VERSION",
        FSDKE_SYNTAX_ERROR => "FSDKE_SYNTAX_ERROR",
        FSDKE_PARAMETER_NOT_FOUND => "FSDKE_PARAMETER_NOT_FOUND",
        FSDKE_INVALID_TEMPLATE => "FSDKE_INVALID_TEMPLATE",
        FSDKE_UNSUPPORTED_TEMPLATE_VERSION => "FSDKE_UNSUPPORTED_TEMPLATE_VERSION",
        FSDKE_CAMERA_INDEX_DOES_NOT_EXIST => "FSDKE_CAMERA_INDEX_DOES_NOT_EXIST",
        FSDKE_PLATFORM_NOT_LICENSED => "FSDKE_PLATFORM_NOT_LICENSED",
        FSDKE_TENSORFLOW_NOT_INITIALIZED => "FSDKE_TENSORFLOW_NOT_INITIALIZED",
        FSDKE_PLUGIN_NOT_LOADED => "FSDKE_PLUGIN_NOT_LOADED",
        FSDKE_PLUGIN_NO_PERMISSION => "FSDKE_PLUGIN_NO_PERMISSION",
        FSDKE_FACEID_NOT_FOUND => "FSDKE_FACEID_NOT_FOUND",
        FSDKE_FACEIMAGE_NOT_FOUND => "FSDKE_FACEIMAGE_NOT_FOUND",
        FSDKE_IBETA_INITIALIZATION_ERROR => "FSDKE_IBETA_INITIALIZATION_ERROR",
        _ => "UNKNOWN_ERROR",
    }
}
